game:
  spawns:
    1:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
      world: world
    2:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
      world: world
    spawn:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
      world: world